Repository prgrms-be-devcourse/NBE1_2_Team07, pull requests merged in 2024-10, with the labels that each got.

#20 Feat/#3 기술 블로그 커밋 1차
  build.gradle
  src/main/java/com/develetter/develetter/DeveletterApplication.java
  src/main/java/com/develetter/develetter/blog/Util/BlogUtil.java
  src/main/java/com/develetter/develetter/blog/controller/InterestController.java
  src/main/java/com/develetter/develetter/blog/controller/SearchController.java
  src/main/java/com/develetter/develetter/blog/entity/Blog.java
  src/main/java/com/develetter/develetter/blog/repository/BlogRepository.java
  src/main/java/com/develetter/develetter/blog/scheduler/BlogScheduler.java
  src/main/java/com/develetter/develetter/blog/scheduler/BlogSchedulerlmpl.java
  src/main/java/com/develetter/develetter/blog/service/InterestService.java
  src/main/java/com/develetter/develetter/blog/service/InterestServicelmpl.java
  src/main/java/com/develetter/develetter/blog/service/SearchService.java
  src/main/java/com/develetter/develetter/blog/service/SearchServicelmpl.java
Labels: Feat

#24 Feat/#22 사람인 채용정보 필터링
  build.gradle
  src/main/java/com/develetter/develetter/global/config/QueryDSLConfig.java
  src/main/java/com/develetter/develetter/jobposting/JobPostingKeyword.java
  src/main/java/com/develetter/develetter/jobposting/UserFilter.java
  src/main/java/com/develetter/develetter/jobposting/UserFilterRepository.java
  src/main/java/com/develetter/develetter/jobposting/controller/JobPostingController.java
  src/main/java/com/develetter/develetter/jobposting/dto/JobSearchParams.java
  src/main/java/com/develetter/develetter/jobposting/entity/FilteredJobPosting.java
  src/main/java/com/develetter/develetter/jobposting/repository/DslJobPostingRepository.java
  src/main/java/com/develetter/develetter/jobposting/repository/DslJobPostingRepositoryImpl.java
  src/main/java/com/develetter/develetter/jobposting/repository/FilteredJobPostingRepository.java
  src/main/java/com/develetter/develetter/jobposting/scheduler/JobPostingSchedulerImpl.java
  src/main/java/com/develetter/develetter/jobposting/service/JobPostingService.java
  src/main/java/com/develetter/develetter/jobposting/service/JobPostingServiceImpl.java
  src/main/java/com/develetter/develetter/mail/service/MailService.java
Labels: Feat

#26 Feat/#4 컨퍼런스 캘린더 첨부 / 메일 발송 체크
  src/main/java/com/develetter/develetter/blog/scheduler/BlogSchedulerlmpl.java
  src/main/java/com/develetter/develetter/mail/converter/Converter.java
  src/main/java/com/develetter/develetter/mail/dto/MailRegisterDto.java
  src/main/java/com/develetter/develetter/mail/dto/MailResDto.java
  src/main/java/com/develetter/develetter/mail/entity/Mail.java
  src/main/java/com/develetter/develetter/mail/repository/MailRepository.java
  src/main/java/com/develetter/develetter/mail/scheduler/MailScheduler.java
  src/main/java/com/develetter/develetter/mail/scheduler/MailSchedulerImpl.java
  src/main/java/com/develetter/develetter/mail/service/AsyncMailService.java
  src/main/java/com/develetter/develetter/mail/service/ConferenceCalendarService.java
  src/main/java/com/develetter/develetter/mail/service/MailService.java
  src/main/java/com/develetter/develetter/mail/service/MailServiceImpl.java
  src/main/resources/templates/conferenceCalendar.html
  src/main/resources/templates/email.html
Labels: Feat

#27 Feat/#25 사용자의 관심 분야에 맞춰 사람인 채용 정보를 필터링하는 기능 Spring Batch로 리팩토링
  src/main/java/com/develetter/develetter/jobposting/batch/JobPostingBatch.java
  src/main/java/com/develetter/develetter/jobposting/controller/JobPostingController.java
  src/main/resources/application.properties
Labels: Refactor

#23 Feat/#2 유저 회원가입 및 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/develetter/develetter/user/controller/UserController.java
  src/main/java/com/develetter/develetter/user/filter/JwtAuthenticationFilter.java
  src/main/java/com/develetter/develetter/user/global/common/ResponseCode.java
  src/main/java/com/develetter/develetter/user/global/common/ResponseMessage.java
  src/main/java/com/develetter/develetter/user/global/common/Role.java
  src/main/java/com/develetter/develetter/user/global/config/WebSecurityConfig.java
  src/main/java/com/develetter/develetter/user/global/dto/LogInResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/CheckCertificationRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/DeleteIdRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/EmailCertificationRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/IdCheckRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/SigninRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/request/SignupRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/CheckCertificationResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/DeleteIdResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/EmailCertificationResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/IdCheckResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/SigninResponseDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/SignupResponseDto.java
  src/main/java/com/develetter/develetter/user/global/entity/CertificationEntity.java
  src/main/java/com/develetter/develetter/user/global/entity/CustomOAuthUser.java
  src/main/java/com/develetter/develetter/user/global/entity/UserEntity.java
  src/main/java/com/develetter/develetter/user/handler/OAuthSuccessHandler.java
  src/main/java/com/develetter/develetter/user/handler/ValidationExceptionHandler.java
  src/main/java/com/develetter/develetter/user/provider/CertificationNumberProvider.java
  src/main/java/com/develetter/develetter/user/provider/EmailProvider.java
  src/main/java/com/develetter/develetter/user/provider/JwtProvider.java
  src/main/java/com/develetter/develetter/user/repository/CertificationRepository.java
  src/main/java/com/develetter/develetter/user/repository/UserRepository.java
  src/main/java/com/develetter/develetter/user/service/UserService.java
  src/main/java/com/develetter/develetter/user/service/implement/OAuthUserServiceImpl.java
  src/main/java/com/develetter/develetter/user/service/implement/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/template/verification-email.html
Labels: Feat

#34 Feat/#33 filtered_blog id를 통해 blog 컬럼 데이터 반환하는 메소드 추가
  src/main/java/com/develetter/develetter/blog/dto/BlogDto.java
  src/main/java/com/develetter/develetter/blog/service/InterestService.java
  src/main/java/com/develetter/develetter/blog/service/InterestServiceImpl.java
Labels: Feat

#32 Feat/#29 Spring Batch의 RepositoryItemReader를 QuerydslNoOffsetPagingItemReader로 변경, 최적화
  src/main/java/com/develetter/develetter/jobposting/batch/JobPostingBatch.java
  src/main/java/com/develetter/develetter/jobposting/batch/QuerydslPagingItemReader.java
Labels: Feat, Refactor

#35 Feat/#31 userId로 채용공고 조회하는 API와 UserFilter 로직 분리
  src/main/java/com/develetter/develetter/blog/scheduler/BlogSchedulerImpl.java
  src/main/java/com/develetter/develetter/jobposting/batch/JobPostingBatch.java
  src/main/java/com/develetter/develetter/jobposting/controller/JobPostingController.java
  src/main/java/com/develetter/develetter/jobposting/converter/Converter.java
  src/main/java/com/develetter/develetter/jobposting/dto/JobPostingEmailDto.java
  src/main/java/com/develetter/develetter/jobposting/dto/JobSearchParams.java
  src/main/java/com/develetter/develetter/jobposting/repository/DslJobPostingRepository.java
  src/main/java/com/develetter/develetter/jobposting/repository/DslJobPostingRepositoryImpl.java
  src/main/java/com/develetter/develetter/jobposting/scheduler/JobPostingSchedulerImpl.java
  src/main/java/com/develetter/develetter/jobposting/service/JobPostingService.java
  src/main/java/com/develetter/develetter/jobposting/service/JobPostingServiceImpl.java
  src/main/java/com/develetter/develetter/userfilter/entity/JobPostingKeyword.java
  src/main/java/com/develetter/develetter/userfilter/entity/UserFilter.java
  src/main/java/com/develetter/develetter/userfilter/repository/UserFilterRepository.java
  src/main/java/com/develetter/develetter/userfilter/service/UserFilterService.java
  src/main/java/com/develetter/develetter/userfilter/service/UserFilterServiceImpl.java
Labels: Feat

#37 Feat/#30 사용자가 받을 수 있는 블로그 글이 없는 상황에 대한 기능 구현
  src/main/java/com/develetter/develetter/blog/repository/FilteredBlogRepository.java
  src/main/java/com/develetter/develetter/blog/scheduler/BlogSchedulerImpl.java
  src/main/java/com/develetter/develetter/blog/service/InterestService.java
  src/main/java/com/develetter/develetter/blog/service/InterestServiceImpl.java
  src/main/java/com/develetter/develetter/blog/service/SearchServiceImpl.java
Labels: Feat

#41 Feat/#38 채용공고 Spring batch를 Scheduler를 통해 활성화
  src/main/java/com/develetter/develetter/jobposting/batch/JobPostingBatch.java
  src/main/java/com/develetter/develetter/jobposting/scheduler/JobPostingSchedulerImpl.java
Labels: Feat

#42 Feat/#40 유저 필터 추가
  src/main/java/com/develetter/develetter/user/repository/CertificationRepository.java
  src/main/java/com/develetter/develetter/user/service/implement/UserServiceImpl.java
  src/main/java/com/develetter/develetter/userfilter/controller/UserFilterController.java
  src/main/java/com/develetter/develetter/userfilter/entity/UserFilter.java
  src/main/java/com/develetter/develetter/userfilter/service/UserFilterServiceImpl.java
Labels: Feat, Fix

#44 Refactor/#43 메일 전송 Spring Batch 리팩토링
  src/main/java/com/develetter/develetter/mail/batch/MailBatch.java
  src/main/java/com/develetter/develetter/mail/config/JobParametersFactory.java
  src/main/java/com/develetter/develetter/mail/converter/Converter.java
  src/main/java/com/develetter/develetter/mail/dto/MailResDto.java
  src/main/java/com/develetter/develetter/mail/repository/MailRepository.java
  src/main/java/com/develetter/develetter/mail/scheduler/MailScheduler.java
  src/main/java/com/develetter/develetter/mail/scheduler/MailSchedulerImpl.java
  src/main/java/com/develetter/develetter/mail/service/AsyncMailService.java
  src/main/java/com/develetter/develetter/mail/service/JobPostingCalendarService.java
  src/main/java/com/develetter/develetter/mail/service/MailService.java
  src/main/java/com/develetter/develetter/mail/service/MailServiceImpl.java
Labels: Refactor

#48 Feat/#47 구독회원 설정로직 추가 및 디버깅
  src/main/java/com/develetter/develetter/user/controller/UserController.java
  src/main/java/com/develetter/develetter/user/global/dto/request/RegisterSubscribeRequestDto.java
  src/main/java/com/develetter/develetter/user/global/dto/response/RegisterSubscribeResponseDto.java
  src/main/java/com/develetter/develetter/user/global/entity/UserEntity.java
  src/main/java/com/develetter/develetter/user/provider/JwtProvider.java
  src/main/java/com/develetter/develetter/user/service/UserService.java
  src/main/java/com/develetter/develetter/user/service/implement/OAuthUserServiceImpl.java
  src/main/java/com/develetter/develetter/user/service/implement/UserServiceImpl.java
Labels: Feat

#46 Refactor/#44 채용 정보 필터링 기능에 Redis 도입
  build.gradle
  src/main/java/com/develetter/develetter/global/config/RedisRepositoryConfig.java
  src/main/java/com/develetter/develetter/jobposting/batch/JobPostingBatch.java
  src/main/java/com/develetter/develetter/jobposting/service/FilteredJobPostingCacheService.java
Labels: Refactor
